services:
  - type: web
    name: english-dictionary-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MONGODB_URI
        sync: false
